### ISSUE TITLE
basepair.models seq_bpnet_cropped_extra_seqlen unavailable

### ISSUE THREAD

**Issue by mPloenzke** [kundajelab/bpnet-manuscript#1]
The model called in bpnet-pipeline/Snakefile -- seq_bpnet_cropped_extra_seqlen -- is not callable and I do not see it available in basepairs.models.py. Which model is this?

**Comment by Avsecz** [comment]
Oh, that was in my old code-base. That's a function to compute the input sequence size. Let me fix this.

**Comment by Avsecz** [comment]
Ok. added the function
